all:
	wget http://code.jquery.com/jquery-2.1.4.min.js
	wget http://underscorejs.org/underscore-min.js
	wget https://login.persona.org/include.js
	mv include.js persona.js
	wget https://github.com/twbs/bootstrap/releases/download/v3.3.6/bootstrap-3.3.6-dist.zip
	unzip bootstrap-3.3.6-dist.zip
	wget https://fb.me/react-0.14.3.js
	wget https://fb.me/react-dom-0.14.3.js
	wget https://github.com/pieroxy/lz-string/archive/1.4.4.zip
	unzip 1.4.4.zip
	wget https://github.com/moment/moment/archive/2.13.0.zip
	unzip 2.13.0.zip
	wget https://github.com/vitalets/combodate/archive/1.0.7.zip
	unzip 1.0.7.zip
